### PR TITLE
[Metrics Code Clone] Fix analysis failure with Lexical error

### LINKED ISSUE #2049: [Metrics Code Clone] exits with Lexical error
On a certain repository, underlying pmd_cpd exits with Lexical error as;

```console
$ pmd_cpd --minimum-tokens 100 --language ecmascript --format xml --failOnViolation false --files .
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file /tmp/d20210210-6-1njgrgt/./wp-includes/js/codemirror/codemirror.min.js at line 12, column 22844.  Encountered: Lexical error at line 12, column 22844.  Encountered: "s" (115), after : "\\" (in lexical state 0)
	at net.sourceforge.pmd.lang.ast.TokenMgrError.withFileName(TokenMgrError.java:124)
	at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:44)
	at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:144)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:139)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:108)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:70)
	at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:80)
	at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:65)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourcesFilesToCPD(CPDCommandLineInterface.java:134)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourceFilesToCPD(CPDCommandLineInterface.java:114)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.main(CPDCommandLineInterface.java:87)
	at net.sourceforge.pmd.cpd.CPD.main(CPD.java:179)
exit status: 1
```

The option `--skip-lexical-errors` skips the error and treats it as a warning.
It is better for Metrics Code Clone to skip such an invalid file, so that it keeps analyzing as many files as possible.

### PR DESCRIPTION
**Pull request by suetsuguk**
This change aims to fix an analysis failure with Lexical error thrown by `pmd_cpd`.
Fix #2049

> Check the following if needed.

- [x] Add a new entry to [CHANGELOG.md](https://github.com/sider/runners/blob/master/CHANGELOG.md) if this change is notable.

### CODE REVIEW

File: lib/runners/processor/pmd_cpd.rb [hunk 1]
```diff
@@ -71,6 +71,10 @@ class Processor::PmdCpd < Processor
 
     register_config_schema(name: :pmd_cpd, schema: Schema.runner_config)
 
+    def force_option_skip_lexical_errors
+      @force_option_skip_lexical_errors = true
+    end
```
Comment (ybiquitous) [inline lib/runners/processor/pmd_cpd.rb:76]: [suggestion] In this case, using `attr_writer` is natural:

```suggestion
    attr_writer :force_option_skip_lexical_errors
```

File: lib/runners/processor/pmd_cpd.rb [hunk 2]
```diff
@@ -191,7 +195,7 @@ def option_non_recursive
     end
 
     def option_skip_lexical_errors
-      config_linter[:'skip-lexical-errors'].then { |v| v ? ["--skip-lexical-errors"] : [] }
+      (@force_option_skip_lexical_errors || config_linter[:'skip-lexical-errors']).then { |v| v ? ["--skip-lexical-errors"] : [] }
```
Comment (ybiquitous) [inline lib/runners/processor/pmd_cpd.rb:198]:
```suggestion
      (force_option_skip_lexical_errors || config_linter[:'skip-lexical-errors']).then { |v| v ? ["--skip-lexical-errors"] : [] }
```

**Comment by suetsuguk** [comment]
I tried to make no changes in existing `pmd_cpd.rb` class, but failed.
1. Any content in the freezing `config_linter` hash cannot be modified.
2. A subclass derived from `PmdCpd` class throws an error;

```ruby
  class Processor::MetricsCodeClone < Processor
    extend Forwardable

    class UnderlyingPmdCpd < Processor::PmdCpd
      def option_skip_lexical_errors
        "--skip-lexical-errors"
     end
    end
    ...
    def initialize(**params)
      super(**params)
      @pmd_cpd = UnderlyingPmdCpd.new(**params)
    end
    ...
  end
```

```console
/home/analyzer_runner/runners/lib/runners/processor/metrics_codeclone.rb:5:in `<class:MetricsCodeClone>': uninitialized constant Runners::Processor::PmdCpd (NameError)
        from /home/analyzer_runner/runners/lib/runners/processor/metrics_codeclone.rb:2:in `<module:Runners>'
        from /home/analyzer_runner/runners/lib/runners/processor/metrics_codeclone.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /home/analyzer_runner/runners/lib/runners.rb:94:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /home/analyzer_runner/runners/exe/runners:5:in `<main>'
```

Do you have any idea? @ybiquitous

**Comment by ybiquitous** [comment]
I think it is acceptable to just add `attr_writer` to the `Processor::PmdCpd` class.

File: lib/runners/processor/pmd_cpd.rb (hunk 2 above)
Comment (ybiquitous) [reply lib/runners/processor/pmd_cpd.rb:196]: Oh, sorry. `attr_accessor` is better than `attr_writer` to avoid using the instance variable `@force_option_skip_lexical_errors` 🙇

File: lib/runners/processor/pmd_cpd.rb (hunk 1 above)
Comment (suetsuguk) [reply lib/runners/processor/pmd_cpd.rb]: Thank you for pointing out. It helps to reduce the number of lines.

File: lib/runners/processor/pmd_cpd.rb (hunk 2 above)
Comment (suetsuguk) [reply lib/runners/processor/pmd_cpd.rb]: Now I got your intention. Thank you.

Comment (suetsuguk) [reply lib/runners/processor/pmd_cpd.rb]: Fixed. commit 2814c799d6779bbd01faf55578bfbaa0b759a3ba

**Review by ybiquitous — APPROVED** [review]
LGTM 👍
