### PR TITLE
Fix "No space left" error on Git workspace

### LINKED ISSUE #951: "No space left on device" error on Git workspace
>  Errno::ENOSPC · No space left on device - copy_file_range 

https://github.com/sider/runners/blob/eb710073dbb23a51c29200e76fc96274a8cf3741/lib/runners/workspace/git.rb#L24-L29

### PR DESCRIPTION
**Pull request by ybiquitous**
This change aims to prevent the "No space left on device" error by stopping a copy of the entire working directory.

https://github.com/sider/runners/blob/48e04a96ee7e477394deb6a836edda3ded5e5c3b/lib/runners/workspace/git.rb#L26

This removal makes the `Workspace::Git` code more simple.

Fix #951

### CODE REVIEW

File: lib/runners/workspace.rb [hunk 1]
```diff
@@ -56,12 +56,6 @@ def open
           yield git_ssh_path, changes
         end
       end
-    ensure
-      FileUtils.remove_entry root_tmp_dir
-    end
-
-    def root_tmp_dir
```
Comment (ybiquitous) [inline lib/runners/workspace.rb:63]: [note] `#root_tmp_dir` is used only in `Workspace::Git`.

File: lib/runners/workspace/git.rb [hunk 2]
```diff
@@ -2,41 +2,23 @@ module Runners
   class Workspace::Git < Workspace
     def range_git_blame_info(path_string, start_line, end_line)
       stdout, _ = shell.capture3!("git", "blame", "-p", "-L", "#{start_line},#{end_line}", git_source.head, "--", path_string,
-                                  trace_stdout: false, trace_stderr: true, chdir: git_directory)
+                                  trace_stdout: false, trace_stderr: true)
```
Comment (ybiquitous) [inline lib/runners/workspace/git.rb:5]: [note] `shell` is always executed in `working_dir`, so I determine all `chdir` in this class are needless.

File: lib/runners/workspace/git.rb [hunk 3]
```diff
@@ -47,9 +29,11 @@ def remote_url
...
 
     def git_fetch_args
-      @git_fetch_args ||= %w[--quiet --no-tags --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/*].tap do |command|
-        pull_number = git_source.pull_number
-        command << "+refs/pull/#{pull_number}/head:refs/remotes/pull/#{pull_number}/head" if pull_number
+      @git_fetch_args ||= %w[--quiet --no-tags --no-recurse-submodules origin].tap do |command|
+        command << "+refs/heads/*:refs/remotes/origin/*"
+
+        num = git_source.pull_number
+        command << "+refs/pull/#{num}/head:refs/remotes/pull/#{num}/head" if num
```
Comment (ybiquitous) [inline lib/runners/workspace/git.rb:36]: [note] Just a refactoring. I want to see both branch names close together.

File: test/workspace/git_test.rb [hunk 4]
```diff
@@ -5,83 +5,86 @@ class WorkspaceGitTest < Minitest::Test
...
+      git_http_url: "https://github.com",
+      owner: "sider",
+      repo: "runners",
+      pull_number: 533,
+    }
+  end
+
+  def workspace_params_with_base
+    workspace_params.merge(base: "abe1cfc294c8d39de7484954bf8c3d7792fd8ad1")
+  end
```
Comment (ybiquitous) [inline test/workspace/git_test.rb:20]: [note] Extract factory methods to make the code readable.

**Comment by ybiquitous** [comment]
We need to exclude the `.git` directory from actual analyses by a tool.

**Comment by ybiquitous** [comment]
If some tools require `.git` for their analysis, then we will provide an opt-in mechanism.

**Comment by ybiquitous** [comment]
@yykamei Could you re-review, please?
