### PR TITLE
Use git-ls-files instead of git-check-ignore

### LINKED ISSUE #1144: `ignore` option does not work
https://sider.review/gh/repos/202486306/pulls/1143/logs/d477d2f5-4776-44d8-b3fb-ced2b68cb216

image

https://github.com/sider/runners/blob/77ab6a3165d8c3796e0d254de0170c234c752bf6/sider.yml#L10-L11

### PR DESCRIPTION
**Pull request by ybiquitous**
[git-check-ignore](https://git-scm.com/docs/git-check-ignore) does not work but I cannot find the cause. 🤷 
So, I will try [git-ls-files](https://git-scm.com/docs/git-ls-files) instead to fix the bug.

Fix #1144

### CODE REVIEW

File: lib/runners/ignoring.rb [hunk 1]
```diff
@@ -10,14 +10,19 @@ def initialize(working_dir:, trace_writer:, config:)
...
     def delete_ignored_files!
-      return if ignores.empty?
+      return [] if ignores.empty?
+
+      # @type var deleted_files: Array[String]
+      deleted_files = []
 
       trace_writer.message("Deleting ignored files...") do
-        with_gitignore do |list|
-          FileUtils.rm_rf list
```
Comment (ybiquitous) [inline lib/runners/ignoring.rb:17]: [note] This deletes each file instead of a file list to know which file fails to delete.

File: lib/runners/ignoring.rb [hunk 2]
```diff
@@ -10,14 +10,19 @@ def initialize(working_dir:, trace_writer:, config:)
...
-          trace_writer.message list.map { |f| f.relative_path_from(working_dir).to_path }.sort.join("\n")
+        each_ignored_file do |file|
+          (working_dir / file).delete
+          deleted_files << file
         end
       end
+
+      deleted_files
```
Comment (ybiquitous) [inline lib/runners/ignoring.rb:25]: [note] This returns a list to make testing easier.

**Comment by ybiquitous** [comment]
Output example:

```
{:trace=>:message, :message=>"Deleting ignored files...", :recorded_at=>"2020-05-26T09:18:17.890Z", :truncated=>false, :duration_in_ms=>0}
{:trace=>:command_line, :command_line=>["git", "init"], :recorded_at=>"2020-05-26T09:18:17.891Z"}
{:trace=>:stdout, :string=>"Initialized empty Git repository in /private/var/folders/w7/xmkvcyt15lgbzwq9ndf52lj00000gq/T/d20200526-69799-nkadfp/.git/", :recorded_at=>"2020-05-26T09:18:17.915Z", :truncated=>false}
{:trace=>:status, :status=>0, :recorded_at=>"2020-05-26T09:18:17.915Z"}
{:trace=>:command_line, :command_line=>["git", "add", "."], :recorded_at=>"2020-05-26T09:18:17.915Z"}
{:trace=>:status, :status=>0, :recorded_at=>"2020-05-26T09:18:17.937Z"}
{:trace=>:command_line, :command_line=>["git", "ls-files", "--ignored", "--exclude-from", "/var/folders/w7/xmkvcyt15lgbzwq9ndf52lj00000gq/T/gitignore-20200526-69799-a193jy"], :recorded_at=>"2020-05-26T09:18:17.937Z"}
{:trace=>:stdout, :string=>"bar", :recorded_at=>"2020-05-26T09:18:17.952Z", :truncated=>false}
{:trace=>:status, :status=>0, :recorded_at=>"2020-05-26T09:18:17.952Z"}
{:trace=>:message, :message=>"-> 0.061s", :recorded_at=>"2020-05-26T09:18:17.952Z", :truncated=>false, :duration_in_ms=>61}
```

**Comment by ybiquitous** [comment]
I will try it anyway. 💪
