### PR TITLE
Drop older versions of ESLint

### LINKED ISSUE #715: Drop ESLint "< 5.0.0"
Drop the support of the older version of ESLint.

https://help.sider.review/news/2019#update-languages-and-tools-on-dec-17-2019
> [Announcement] We are planning to drop the support of ESLint and RuboCop older versions on January 31, 2020. After the deadline, all analyses by the older versions will fail. If you are using the older versions, please upgrade them by the deadline. Here are new versions:
> * ESLint 5.0.0+
> * RuboCop 0.61.0+

### PR DESCRIPTION
**Pull request by yykamei**
Close #715

### CODE REVIEW

File: test/smokes/eslint/expectations.rb [hunk 1]
```diff
@@ -30,44 +30,6 @@
   }
 )
 
-Smoke.add_test(
-  "sideci_valid_npm_install_option",
```
Comment (yykamei) [inline test/smokes/eslint/expectations.rb]: I think this test is no longer necessary because other tests are checking the validity of `sider.yml`.

File: test/smokes/eslint/expectations.rb [hunk 2]
```diff
@@ -78,157 +40,37 @@
...
-    ESLint couldn't find the plugin "eslint-plugin-filenames".
+          ESLint couldn't find the plugin "eslint-plugin-filenames".
   MESSAGE
       ),
     analyzer: { name: "ESLint", version: "6.8.0" }
   }
 )
 
 Smoke.add_test(
-  "dir_option_is_array",
```
Comment (yykamei) [inline test/smokes/eslint/expectations.rb]: This test should be written as a unit test. In the first place, testing this feature is overplaying to me.

File: test/smokes/eslint/expectations.rb [hunk 3]
```diff
@@ -78,157 +40,37 @@
...
+  }
 )
 
 Smoke.add_test(
   "no_files",
   { guid: "test-guid", timestamp: :_, type: "success", issues: [], analyzer: { name: "ESLint", version: "6.8.0" } }
 )
 
-Smoke.add_test(
-  "no_files_eslint4",
```
Comment (yykamei) [inline test/smokes/eslint/expectations.rb]: This test is satisfied with `pinned_old_eslint`.

File: lib/runners/processor/eslint.rb [hunk 4]
```diff
@@ -59,7 +58,6 @@ def setup
           return Results::Failure.new(guid: guid, message: exn.message, analyzer: nil)
         end
         analyzer
-        add_warning_if_deprecated_version(minimum: RECOMMENDED_MINIMUM_VERSION, file: "package.json", deadline: Time.new(2020, 1, 31))
         yield
       end
     end
```
Comment (ybiquitous) [inline lib/runners/processor/eslint.rb]: It seems we can fix also this:

https://github.com/sider/runners/blob/027d777ca046d671f32671d764cddb78997569b7/lib/runners/processor/eslint.rb#L246-L249

Comment (yykamei) [reply lib/runners/processor/eslint.rb]: Thank you. Is [this](7772312) correct?

Comment (ybiquitous) [reply lib/runners/processor/eslint.rb]: Looks good!

BTW, `[this](7772312)` link points to "404 Not Found" 😅
